import { Container } from "@/components/ui/Wrappers";
import ProductCart from "@/components/ui/product/ProductCart";
import { Grid } from "@/components/ui/Wrappers";
export default function Home() {
  return (
    <main>
      <Container>
        <Grid>
          <ProductCart
            category="dwqd"
            image="/images/475.jpg"
            href="/ddq"
            title="qddqqd"
            price="312"
          />
          <ProductCart
            category="dwqd"
            image="/images/475.jpg"
            href="/ddq"
            title="qddqqd"
            price="312"
          />
          <ProductCart
            category="dwqd"
            image="/images/475.jpg"
            href="/ddq"
            title="qddqqd"
            price="312"
          />
          <ProductCart
            category="dwqd"
            image="/images/475.jpg"
            href="/ddq"
            title="qddqqd"
            price="312"
          />
          <ProductCart
            category="dwqd"
            image="/images/475.jpg"
            href="/ddq"
            title="qddqqd"
            price="312"
          />
          <ProductCart
            category="dwqd"
            image="/images/475.jpg"
            href="/ddq"
            title="qddqqd"
            price="312"
          />
          <ProductCart
            category="dwqd"
            image="/images/475.jpg"
            href="/ddq"
            title="qddqqd"
            price="312"
          />
          <ProductCart
            category="dwqd"
            image="/images/475.jpg"
            href="/ddq"
            title="qddqqd"
            price="312"
          />
          <ProductCart
            category="dwqd"
            image="/images/475.jpg"
            href="/ddq"
            title="qddqqd"
            price="312"
          />
          <ProductCart
            category="dwqd"
            image="/images/475.jpg"
            href="/ddq"
            title="qddqqd"
            price="312"
          />
        </Grid>
      </Container>
    </main>
  );
}
